### ISSUE TITLE
Script tags

### ISSUE THREAD

**Issue by nwhite89** [junmer/html2js#3]
Hey

I'm running into an issue using ``html2js`` when dealing with ``<script>`` tags with JS (so you can write them out the end tag needs to be amended like: 

```js
html2Js(body, {
  mode: 'default', 
  wrap: false
})
.replace(/<\/script/g, '<\/\'+\'script');
```

What do you feel about automatically dealing with script tags? or at least passing something to set that you want this done?

**Comment by junmer** [comment]
@nwhite89  good case, i have added this feature use your idea, thanks

**Comment by nwhite89** [comment]
awesome thanks @junmer :+1: any chance to get a heads up when this is implemented? then I can delete some code :) cheers

**Comment by junmer** [comment]
I add option `ignoreScriptTag` defaults to `false`, so, you can rm your code direct. :smile: 

> `ignoreScriptTag`: boolean to ignore fix [split the script tag when writing it with document write](http://stackoverflow.com/questions/236073/why-split-the-script-tag-when-writing-it-with-document-write). Defaults to `false`

**Comment by nwhite89** [comment]
:smile: I more meant when you did a release but awesome thank you! Keep up the good work @junmer

**Comment by junmer** [comment]
@nwhite89 thanks for your support :smiley:
